### PR TITLE
Bug 1136309 - Document the new spidermonkey builds

### PR DESCRIPTION
**Pull request by hotsphink**
Is this what I'm supposed to do? I force-pushed an amended commit, then made a new PR with it.

### CODE REVIEW

**Comment by tojonmz** [comment]
Sure, this is ok for this instance. Normally though you can leave the first PR open (https://github.com/mozilla/treeherder-ui/pull/395) and just force push to your remote (origin). Your --amend would be reflected in that PR.

For now, this one time is ok though.

That way we don't end up with tons of closed PR's which didn't result in any code changes.

**Comment by tojonmz** [comment]
Oh, yes and you can find it on IRC in #treeherder if you have any questions, too.

**Comment by tojonmz** [comment]
Oh, and I see @edmorley r+'d the original attachment to the bug, but if you want a second check, you can:

* paste the url to this PR as a 'text attachment' to the bug
* title the attachment as something... eg. "treeherder-ui-PR#396"
* set Ed as the reviewer again on that attachment

I'll defer to Ed until we hear back just to be safe. I'm just not sure if there have been changes since his patch review.

**Comment by edmorley** [comment]
I'm fine to merge now :-)

**Comment by tojonmz** [comment]
Thanks Ed!

**Pull request merged**
