### PR TITLE
Bug 1137425 - Fixed annotation classification deletion

### PR DESCRIPTION
**Pull request by dewgeek**
while updating ThResultSetModel in all the controllers, It is not updated in this file, because of which, we are unable to delete classifications .

### CODE REVIEW

**Comment by tojonmz** [comment]
@dewgeek can you provide a more referenced commit message? eg. 'Bug 1137425 - Fixed annotation classification deletion" etc. Thanks.

**Comment by dewgeek** [comment]
@tojonmz , sorry about that. :)

**Comment by tojonmz** [comment]
No, actually we want the commit message itself to have that `Bug 1137425 - Fixed classification deletion` message, not just the title of the PR.

All commits with rare exception should be prefixed with `Bug nnnnnn - ` so we know what bug the commit was fixing, when we look at the git log history.

**Comment by camd** [comment]
@dewgeek Looks like we can close this PR, as it was subsumed by the PR for Bug 1113396

**Pull request closed without merging**
