### PR TITLE
Bug 1162201 - Tweaks to frontend UI

### PR DESCRIPTION
**Pull request by wlach**
[Review on Reviewable](https://reviewable.io/reviews/mozilla/treeherder-ui/512)

### CODE REVIEW

**Comment by edmorley** [comment]
The png needs to be git added.
Did you mean to change the Treeherder favicon at the same time?
The tree favicon isn't great, but I'm not sure the graph one is any better for Treeherder itself? :-)

**Comment by wlach** [comment]
Oops, thanks for noticing that! No, I left the tree icon for treeherder. :) We should try to find a graphic designer to do some proper icons at some point.

**Comment by edmorley** [comment]
webapp/app/index.html was modified as well as webapp/app/perf.html? :-)
Yeah agree - that would be good!

**Comment by wlach** [comment]
Oh, you're right! That was unintentional, will fix.

**Comment by jmaher** [comment]
oh, these changes are cool!

**Pull request merged**
